name: Generate Snake

on:
  schedule:
    - cron: "0 1,9,17 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Yulfayin
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
            github-snake-dracula.svg?color_snake=%23bd93f9&color_dots=%23282a36,%2344475a,%236272a4,%23bd93f9,%23ff79c6

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-snake.svg github-snake-dark.svg github-snake-dracula.svg
          git commit -m "BOT: update snake" || exit 0
          git push